name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Julia
      uses: julia-actions/setup-julia@latest
      with:
        version: '1.x'
    - name: Run tests
      run: |
        julia --project=@. -e 'using Pkg; Pkg.instantiate();'
        julia --project=@. -e 'using Pkg; Pkg.test();'
